# Generated by Django 4.1.7 on 2023-04-02 16:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guser', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Subject', models.CharField(max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Type_of_complaint', models.CharField(choices=[('Faculty', 'Faculty'), ('Academics', 'Academics'), ('Canteen', 'Canteen'), ('Examination', 'Examination'), ('Fees', 'Fees'), ('Hostel', 'Hostel'), ('Transport', 'Transport'), ('Management', 'Management'), ('Other', 'Other')], max_length=200, null=True)),
                ('To', models.CharField(choices=[('CIVIL HOD', 'CIVIL HOD'), ('CSE HOD', 'CSE HOD'), ('ECE HOD', 'ECE HOD'), ('ECM HOD', 'ECM HOD'), ('EEE HOD', 'EEE HOD'), ('IT HOD', 'IT HOD'), ('MECH HOD', 'MECH HOD'), ('MBA HOD', 'MBA HOD'), ('MANAGEMENT', 'MANAGEMENT'), ('PRINCIPLE', 'PRINCIPLE'), ('DIRECTOR', 'DIRECTOR'), ('CEO', 'CEO')], max_length=200, null=True)),
                ('From_Branch', models.CharField(choices=[('CIVIL', 'CIVIL'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('ECM', 'ECM'), ('EEE', 'EEE'), ('IT', 'IT'), ('MBA', 'MBA'), ('MECH', 'MECH')], max_length=200, null=True)),
                ('Description', models.TextField(max_length=4000, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Solved'), (2, 'InProgress'), (3, 'Pending')], default=3)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
