# Generated by Django 4.1.7 on 2023-04-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='remarks',
            field=models.TextField(max_length=4000, null=True),
        ),
    ]
