# Generated by Django 4.1.7 on 2023-04-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_complaint_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='To',
            field=models.CharField(choices=[('CIVIL HOD', 'CIVIL HOD'), ('CSE_HOD', 'CSE_HOD'), ('ECE HOD', 'ECE HOD'), ('ECM HOD', 'ECM HOD'), ('EEE HOD', 'EEE HOD'), ('IT HOD', 'IT HOD'), ('MECH HOD', 'MECH HOD'), ('MBA HOD', 'MBA HOD'), ('MANAGEMENT', 'MANAGEMENT'), ('PRINCIPLE', 'PRINCIPLE'), ('DIRECTOR', 'DIRECTOR'), ('CEO', 'CEO')], max_length=200, null=True),
        ),
    ]
