# Generated by Django 4.1.7 on 2023-04-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_complaint_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timer', models.CharField(max_length=100)),
            ],
        ),
    ]
