# Generated by Django 4.1.7 on 2023-04-02 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_countdown'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Countdown',
        ),
        migrations.AddField(
            model_name='complaint',
            name='timer',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
