# Generated by Django 4.1.7 on 2023-04-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_complaint_remarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
