# Generated by Django 4.1.7 on 2023-04-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_complaint_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-updated', '-created', 'severity']},
        ),
        migrations.AddField(
            model_name='complaint',
            name='severity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
