# Generated by Django 4.1.7 on 2023-04-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='complaint',
            name='allocated_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
    ]
