# Generated by Django 4.1.7 on 2023-04-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_delete_student_complaint_allocated_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='current_handler',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
